language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dhedgerod/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dhedgerod/docker-react npm run