language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dhedgerod/docker-react .

script:
  - docker run -e CI=true dhedgerod/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: Dockerreact-env
  bucket_name: "elasticbeanstalk-us-east-2-495128236375"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY